// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/example/example_service_general.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Empty used when an RPC doesn't need to return any message
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd08aed30b73de23, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// CreateTopicRequest :nodoc:
type CreateRequestExample struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequestExample) Reset()         { *m = CreateRequestExample{} }
func (m *CreateRequestExample) String() string { return proto.CompactTextString(m) }
func (*CreateRequestExample) ProtoMessage()    {}
func (*CreateRequestExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd08aed30b73de23, []int{1}
}

func (m *CreateRequestExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequestExample.Unmarshal(m, b)
}
func (m *CreateRequestExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequestExample.Marshal(b, m, deterministic)
}
func (m *CreateRequestExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequestExample.Merge(m, src)
}
func (m *CreateRequestExample) XXX_Size() int {
	return xxx_messageInfo_CreateRequestExample.Size(m)
}
func (m *CreateRequestExample) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequestExample.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequestExample proto.InternalMessageInfo

func (m *CreateRequestExample) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// DeleteByIDRequest can be used to many kind of objects
type DeleteByIDRequestExample struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	ObjectId             int64    `protobuf:"varint,2,opt,name=object_id,json=objectId,proto3" json:"object_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByIDRequestExample) Reset()         { *m = DeleteByIDRequestExample{} }
func (m *DeleteByIDRequestExample) String() string { return proto.CompactTextString(m) }
func (*DeleteByIDRequestExample) ProtoMessage()    {}
func (*DeleteByIDRequestExample) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd08aed30b73de23, []int{2}
}

func (m *DeleteByIDRequestExample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByIDRequestExample.Unmarshal(m, b)
}
func (m *DeleteByIDRequestExample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByIDRequestExample.Marshal(b, m, deterministic)
}
func (m *DeleteByIDRequestExample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByIDRequestExample.Merge(m, src)
}
func (m *DeleteByIDRequestExample) XXX_Size() int {
	return xxx_messageInfo_DeleteByIDRequestExample.Size(m)
}
func (m *DeleteByIDRequestExample) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByIDRequestExample.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByIDRequestExample proto.InternalMessageInfo

func (m *DeleteByIDRequestExample) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteByIDRequestExample) GetObjectId() int64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.content.Empty")
	proto.RegisterType((*CreateRequestExample)(nil), "pb.content.CreateRequestExample")
	proto.RegisterType((*DeleteByIDRequestExample)(nil), "pb.content.DeleteByIDRequestExample")
}

func init() {
	proto.RegisterFile("pb/example/example_service_general.proto", fileDescriptor_fd08aed30b73de23)
}

var fileDescriptor_fd08aed30b73de23 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x48, 0xd2, 0x4f,
	0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x85, 0xd1, 0xf1, 0xc5, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9,
	0xf1, 0xe9, 0xa9, 0x79, 0xa9, 0x45, 0x89, 0x39, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x5c,
	0x05, 0x49, 0x7a, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x4a, 0xec, 0x5c, 0xac, 0xae, 0xb9,
	0x05, 0x25, 0x95, 0x4a, 0xfa, 0x5c, 0x22, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x41, 0xa9, 0x85,
	0xa5, 0xa9, 0xc5, 0x25, 0xae, 0x10, 0x23, 0x84, 0xc4, 0xb9, 0xd8, 0x4b, 0x8b, 0x53, 0x8b, 0xe2,
	0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0xd8, 0x40, 0x5c, 0xcf, 0x14, 0xa5, 0x00,
	0x2e, 0x09, 0x97, 0xd4, 0x9c, 0xd4, 0x92, 0x54, 0xa7, 0x4a, 0x4f, 0x17, 0x22, 0x35, 0x09, 0x49,
	0x73, 0x71, 0xe6, 0x27, 0x65, 0xa5, 0x26, 0x97, 0x80, 0xa4, 0x98, 0xc0, 0x52, 0x1c, 0x10, 0x01,
	0xcf, 0x14, 0x27, 0xce, 0x28, 0x76, 0xa8, 0xc3, 0x93, 0xd8, 0xc0, 0x2e, 0x35, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x2b, 0xc1, 0xfd, 0xd5, 0x00, 0x00, 0x00,
}
