// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/content/content_service_topic.proto

package content

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// UpdateTopicByIDRequest :nodoc:
type UpdateTopicByIDRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	TopicId              int64    `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id"`
	Body                 *Topic   `protobuf:"bytes,3,opt,name=body,proto3" json:"body"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTopicByIDRequest) Reset()         { *m = UpdateTopicByIDRequest{} }
func (m *UpdateTopicByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTopicByIDRequest) ProtoMessage()    {}
func (*UpdateTopicByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f37604510466d9d, []int{0}
}

func (m *UpdateTopicByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTopicByIDRequest.Unmarshal(m, b)
}
func (m *UpdateTopicByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTopicByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTopicByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTopicByIDRequest.Merge(m, src)
}
func (m *UpdateTopicByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTopicByIDRequest.Size(m)
}
func (m *UpdateTopicByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTopicByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTopicByIDRequest proto.InternalMessageInfo

func (m *UpdateTopicByIDRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateTopicByIDRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *UpdateTopicByIDRequest) GetBody() *Topic {
	if m != nil {
		return m.Body
	}
	return nil
}

// UpdateMetaTopicByIDRequest :nodoc:
type UpdateMetaTopicByIDRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	TopicId              int64    `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id"`
	MetaKeywords         string   `protobuf:"bytes,3,opt,name=meta_keywords,json=metaKeywords,proto3" json:"meta_keywords"`
	MetaDescription      string   `protobuf:"bytes,4,opt,name=meta_description,json=metaDescription,proto3" json:"meta_description"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetaTopicByIDRequest) Reset()         { *m = UpdateMetaTopicByIDRequest{} }
func (m *UpdateMetaTopicByIDRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetaTopicByIDRequest) ProtoMessage()    {}
func (*UpdateMetaTopicByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f37604510466d9d, []int{1}
}

func (m *UpdateMetaTopicByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetaTopicByIDRequest.Unmarshal(m, b)
}
func (m *UpdateMetaTopicByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetaTopicByIDRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMetaTopicByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetaTopicByIDRequest.Merge(m, src)
}
func (m *UpdateMetaTopicByIDRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMetaTopicByIDRequest.Size(m)
}
func (m *UpdateMetaTopicByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetaTopicByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetaTopicByIDRequest proto.InternalMessageInfo

func (m *UpdateMetaTopicByIDRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateMetaTopicByIDRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *UpdateMetaTopicByIDRequest) GetMetaKeywords() string {
	if m != nil {
		return m.MetaKeywords
	}
	return ""
}

func (m *UpdateMetaTopicByIDRequest) GetMetaDescription() string {
	if m != nil {
		return m.MetaDescription
	}
	return ""
}

// CreateTopicRequest :nodoc:
type CreateTopicRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Body                 *Topic   `protobuf:"bytes,2,opt,name=body,proto3" json:"body"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicRequest) Reset()         { *m = CreateTopicRequest{} }
func (m *CreateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicRequest) ProtoMessage()    {}
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f37604510466d9d, []int{2}
}

func (m *CreateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicRequest.Unmarshal(m, b)
}
func (m *CreateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicRequest.Merge(m, src)
}
func (m *CreateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicRequest.Size(m)
}
func (m *CreateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicRequest proto.InternalMessageInfo

func (m *CreateTopicRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateTopicRequest) GetBody() *Topic {
	if m != nil {
		return m.Body
	}
	return nil
}

// IsTopicFollowedByUserIDRequest :nodoc:
type IsTopicFollowedByUserIDRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	TopicId              int64    `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsTopicFollowedByUserIDRequest) Reset()         { *m = IsTopicFollowedByUserIDRequest{} }
func (m *IsTopicFollowedByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*IsTopicFollowedByUserIDRequest) ProtoMessage()    {}
func (*IsTopicFollowedByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f37604510466d9d, []int{3}
}

func (m *IsTopicFollowedByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsTopicFollowedByUserIDRequest.Unmarshal(m, b)
}
func (m *IsTopicFollowedByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsTopicFollowedByUserIDRequest.Marshal(b, m, deterministic)
}
func (m *IsTopicFollowedByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsTopicFollowedByUserIDRequest.Merge(m, src)
}
func (m *IsTopicFollowedByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_IsTopicFollowedByUserIDRequest.Size(m)
}
func (m *IsTopicFollowedByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsTopicFollowedByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsTopicFollowedByUserIDRequest proto.InternalMessageInfo

func (m *IsTopicFollowedByUserIDRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *IsTopicFollowedByUserIDRequest) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

// ObtainTopicStatisticsResponse :nodoc:
type ObtainTopicStatisticsByIDResponse struct {
	Followers            int64    `protobuf:"varint,1,opt,name=followers,proto3" json:"followers"`
	Readers              int64    `protobuf:"varint,2,opt,name=readers,proto3" json:"readers"`
	Editorials           int64    `protobuf:"varint,3,opt,name=editorials,proto3" json:"editorials"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObtainTopicStatisticsByIDResponse) Reset()         { *m = ObtainTopicStatisticsByIDResponse{} }
func (m *ObtainTopicStatisticsByIDResponse) String() string { return proto.CompactTextString(m) }
func (*ObtainTopicStatisticsByIDResponse) ProtoMessage()    {}
func (*ObtainTopicStatisticsByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f37604510466d9d, []int{4}
}

func (m *ObtainTopicStatisticsByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObtainTopicStatisticsByIDResponse.Unmarshal(m, b)
}
func (m *ObtainTopicStatisticsByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObtainTopicStatisticsByIDResponse.Marshal(b, m, deterministic)
}
func (m *ObtainTopicStatisticsByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObtainTopicStatisticsByIDResponse.Merge(m, src)
}
func (m *ObtainTopicStatisticsByIDResponse) XXX_Size() int {
	return xxx_messageInfo_ObtainTopicStatisticsByIDResponse.Size(m)
}
func (m *ObtainTopicStatisticsByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObtainTopicStatisticsByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObtainTopicStatisticsByIDResponse proto.InternalMessageInfo

func (m *ObtainTopicStatisticsByIDResponse) GetFollowers() int64 {
	if m != nil {
		return m.Followers
	}
	return 0
}

func (m *ObtainTopicStatisticsByIDResponse) GetReaders() int64 {
	if m != nil {
		return m.Readers
	}
	return 0
}

func (m *ObtainTopicStatisticsByIDResponse) GetEditorials() int64 {
	if m != nil {
		return m.Editorials
	}
	return 0
}

// SetTopicMenuByIDTopicRequest :nodoc:
type SetTopicMenuByIDRequest struct {
	UserId               int64      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Body                 *TopicMenu `protobuf:"bytes,2,opt,name=body,proto3" json:"body"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetTopicMenuByIDRequest) Reset()         { *m = SetTopicMenuByIDRequest{} }
func (m *SetTopicMenuByIDRequest) String() string { return proto.CompactTextString(m) }
func (*SetTopicMenuByIDRequest) ProtoMessage()    {}
func (*SetTopicMenuByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f37604510466d9d, []int{5}
}

func (m *SetTopicMenuByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetTopicMenuByIDRequest.Unmarshal(m, b)
}
func (m *SetTopicMenuByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetTopicMenuByIDRequest.Marshal(b, m, deterministic)
}
func (m *SetTopicMenuByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetTopicMenuByIDRequest.Merge(m, src)
}
func (m *SetTopicMenuByIDRequest) XXX_Size() int {
	return xxx_messageInfo_SetTopicMenuByIDRequest.Size(m)
}
func (m *SetTopicMenuByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetTopicMenuByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetTopicMenuByIDRequest proto.InternalMessageInfo

func (m *SetTopicMenuByIDRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SetTopicMenuByIDRequest) GetBody() *TopicMenu {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateTopicByIDRequest)(nil), "pb.content.UpdateTopicByIDRequest")
	proto.RegisterType((*UpdateMetaTopicByIDRequest)(nil), "pb.content.UpdateMetaTopicByIDRequest")
	proto.RegisterType((*CreateTopicRequest)(nil), "pb.content.CreateTopicRequest")
	proto.RegisterType((*IsTopicFollowedByUserIDRequest)(nil), "pb.content.IsTopicFollowedByUserIDRequest")
	proto.RegisterType((*ObtainTopicStatisticsByIDResponse)(nil), "pb.content.ObtainTopicStatisticsByIDResponse")
	proto.RegisterType((*SetTopicMenuByIDRequest)(nil), "pb.content.SetTopicMenuByIDRequest")
}

func init() {
	proto.RegisterFile("pb/content/content_service_topic.proto", fileDescriptor_5f37604510466d9d)
}

var fileDescriptor_5f37604510466d9d = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x61, 0x4b, 0xe3, 0x40,
	0x10, 0x86, 0x49, 0x5b, 0x9a, 0xeb, 0xdc, 0x1d, 0x77, 0xb7, 0x70, 0x6d, 0xae, 0x1c, 0xa5, 0x97,
	0x43, 0x69, 0xbf, 0x44, 0xd0, 0x7f, 0x50, 0x8b, 0x10, 0xa4, 0x08, 0x69, 0xfb, 0x45, 0x90, 0x90,
	0x64, 0x47, 0x58, 0xac, 0xd9, 0xb8, 0x3b, 0xb5, 0x04, 0xff, 0x8c, 0x3f, 0x55, 0x76, 0x93, 0xd2,
	0x8a, 0xa0, 0x82, 0x7e, 0x0a, 0xf3, 0xbc, 0x93, 0x77, 0x66, 0xde, 0x04, 0x0e, 0x8b, 0xf4, 0x28,
	0x93, 0x39, 0x61, 0x4e, 0xdb, 0x67, 0xac, 0x51, 0xdd, 0x8b, 0x0c, 0x63, 0x92, 0x85, 0xc8, 0x82,
	0x42, 0x49, 0x92, 0x0c, 0x8a, 0x34, 0xa8, 0xf5, 0x7e, 0x77, 0xef, 0x9d, 0xbd, 0x1e, 0x5f, 0x43,
	0x77, 0x59, 0xf0, 0x84, 0x70, 0x61, 0xe0, 0xa4, 0x0c, 0xa7, 0x11, 0xde, 0xad, 0x51, 0x13, 0xeb,
	0x81, 0xbb, 0xd6, 0xa8, 0x62, 0xc1, 0x3d, 0x67, 0xe8, 0x8c, 0x9a, 0x51, 0xdb, 0x94, 0x21, 0x67,
	0x7f, 0xe0, 0x8b, 0x75, 0x30, 0x4a, 0xc3, 0x2a, 0xae, 0xad, 0x43, 0xce, 0x0e, 0xa0, 0x95, 0x4a,
	0x5e, 0x7a, 0xcd, 0xa1, 0x33, 0xfa, 0x7a, 0xfc, 0x2b, 0xd8, 0x2d, 0x10, 0x58, 0xff, 0xc8, 0xca,
	0xfe, 0xa3, 0x03, 0xfd, 0x6a, 0xea, 0x0c, 0x29, 0xf9, 0x94, 0xc9, 0xff, 0xe1, 0xfb, 0x2d, 0x52,
	0x12, 0xdf, 0x60, 0xb9, 0x91, 0x8a, 0x6b, 0xbb, 0x42, 0x27, 0xfa, 0x66, 0xe0, 0x79, 0xcd, 0xd8,
	0x18, 0x7e, 0xda, 0x26, 0x8e, 0x3a, 0x53, 0xa2, 0x20, 0x21, 0x73, 0xaf, 0x65, 0xfb, 0x7e, 0x18,
	0x3e, 0xdd, 0x61, 0x7f, 0x01, 0xec, 0x54, 0xe1, 0x36, 0x97, 0x37, 0x37, 0xdb, 0x1e, 0xde, 0x78,
	0xfd, 0xf0, 0x05, 0x0c, 0x42, 0x6d, 0xc1, 0x99, 0x5c, 0xad, 0xe4, 0x06, 0xf9, 0xa4, 0x5c, 0x1a,
	0x87, 0x8f, 0xdc, 0xee, 0x3f, 0xc0, 0xbf, 0x8b, 0x94, 0x12, 0x91, 0x5b, 0xe7, 0x39, 0x25, 0x24,
	0x34, 0x89, 0x4c, 0x57, 0x99, 0xea, 0x42, 0xe6, 0x1a, 0xd9, 0x5f, 0xe8, 0x5c, 0x57, 0x33, 0x95,
	0xae, 0xad, 0x77, 0x80, 0x79, 0xe0, 0x2a, 0x4c, 0xb8, 0xd1, 0x6a, 0xf3, 0xba, 0x64, 0x03, 0x00,
	0xe4, 0x82, 0xa4, 0x12, 0xc9, 0xaa, 0x4a, 0xb5, 0x19, 0xed, 0x11, 0xff, 0x0a, 0x7a, 0x73, 0x24,
	0x3b, 0x79, 0x86, 0xf9, 0xfa, 0x5d, 0xdf, 0x71, 0xfc, 0x2c, 0xad, 0xdf, 0x2f, 0xd2, 0x32, 0x46,
	0x55, 0x62, 0x93, 0xce, 0xa5, 0x5b, 0x4b, 0x69, 0xdb, 0xfe, 0xb1, 0x27, 0x4f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x60, 0x31, 0xdc, 0x69, 0xff, 0x02, 0x00, 0x00,
}
