// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/content/topic.proto

package content

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Topic struct {
	Id                      int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                    string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Slug                    string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug"`
	Description             string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	IsActive                bool     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active"`
	IsPrivate               bool     `protobuf:"varint,6,opt,name=is_private,json=isPrivate,proto3" json:"is_private"`
	IsSpecial               bool     `protobuf:"varint,7,opt,name=is_special,json=isSpecial,proto3" json:"is_special"`
	IsShowTopicCover        bool     `protobuf:"varint,8,opt,name=is_show_topic_cover,json=isShowTopicCover,proto3" json:"is_show_topic_cover"`
	CoverMediaId            int64    `protobuf:"varint,9,opt,name=cover_media_id,json=coverMediaId,proto3" json:"cover_media_id"`
	CreatedAt               string   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt               string   `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	DeletedAt               string   `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	IsActiveCollectionTopic bool     `protobuf:"varint,13,opt,name=is_active_collection_topic,json=isActiveCollectionTopic,proto3" json:"is_active_collection_topic"`
	IsCollectionTopic       bool     `protobuf:"varint,14,opt,name=is_collection_topic,json=isCollectionTopic,proto3" json:"is_collection_topic"`
	CreatedBy               int64    `protobuf:"varint,15,opt,name=created_by,json=createdBy,proto3" json:"created_by"`
	LastUpdatedBy           int64    `protobuf:"varint,16,opt,name=last_updated_by,json=lastUpdatedBy,proto3" json:"last_updated_by"`
	MetaName                string   `protobuf:"bytes,17,opt,name=meta_name,json=metaName,proto3" json:"meta_name"`
	MetaDescription         string   `protobuf:"bytes,18,opt,name=meta_description,json=metaDescription,proto3" json:"meta_description"`
	MetaKeywords            string   `protobuf:"bytes,19,opt,name=meta_keywords,json=metaKeywords,proto3" json:"meta_keywords"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8be1b8620e66274, []int{0}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Topic) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Topic) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Topic) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *Topic) GetIsSpecial() bool {
	if m != nil {
		return m.IsSpecial
	}
	return false
}

func (m *Topic) GetIsShowTopicCover() bool {
	if m != nil {
		return m.IsShowTopicCover
	}
	return false
}

func (m *Topic) GetCoverMediaId() int64 {
	if m != nil {
		return m.CoverMediaId
	}
	return 0
}

func (m *Topic) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Topic) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Topic) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func (m *Topic) GetIsActiveCollectionTopic() bool {
	if m != nil {
		return m.IsActiveCollectionTopic
	}
	return false
}

func (m *Topic) GetIsCollectionTopic() bool {
	if m != nil {
		return m.IsCollectionTopic
	}
	return false
}

func (m *Topic) GetCreatedBy() int64 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *Topic) GetLastUpdatedBy() int64 {
	if m != nil {
		return m.LastUpdatedBy
	}
	return 0
}

func (m *Topic) GetMetaName() string {
	if m != nil {
		return m.MetaName
	}
	return ""
}

func (m *Topic) GetMetaDescription() string {
	if m != nil {
		return m.MetaDescription
	}
	return ""
}

func (m *Topic) GetMetaKeywords() string {
	if m != nil {
		return m.MetaKeywords
	}
	return ""
}

type Topics struct {
	Topics               []*Topic `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topics) Reset()         { *m = Topics{} }
func (m *Topics) String() string { return proto.CompactTextString(m) }
func (*Topics) ProtoMessage()    {}
func (*Topics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8be1b8620e66274, []int{1}
}

func (m *Topics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topics.Unmarshal(m, b)
}
func (m *Topics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topics.Marshal(b, m, deterministic)
}
func (m *Topics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topics.Merge(m, src)
}
func (m *Topics) XXX_Size() int {
	return xxx_messageInfo_Topics.Size(m)
}
func (m *Topics) XXX_DiscardUnknown() {
	xxx_messageInfo_Topics.DiscardUnknown(m)
}

var xxx_messageInfo_Topics proto.InternalMessageInfo

func (m *Topics) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type TopicMenu struct {
	TopicId              int64    `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id"`
	Position             int64    `protobuf:"varint,2,opt,name=position,proto3" json:"position"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	DeletedAt            string   `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicMenu) Reset()         { *m = TopicMenu{} }
func (m *TopicMenu) String() string { return proto.CompactTextString(m) }
func (*TopicMenu) ProtoMessage()    {}
func (*TopicMenu) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8be1b8620e66274, []int{2}
}

func (m *TopicMenu) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicMenu.Unmarshal(m, b)
}
func (m *TopicMenu) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicMenu.Marshal(b, m, deterministic)
}
func (m *TopicMenu) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicMenu.Merge(m, src)
}
func (m *TopicMenu) XXX_Size() int {
	return xxx_messageInfo_TopicMenu.Size(m)
}
func (m *TopicMenu) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicMenu.DiscardUnknown(m)
}

var xxx_messageInfo_TopicMenu proto.InternalMessageInfo

func (m *TopicMenu) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *TopicMenu) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *TopicMenu) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *TopicMenu) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *TopicMenu) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Topic)(nil), "pb.content.Topic")
	proto.RegisterType((*Topics)(nil), "pb.content.Topics")
	proto.RegisterType((*TopicMenu)(nil), "pb.content.TopicMenu")
}

func init() { proto.RegisterFile("pb/content/topic.proto", fileDescriptor_f8be1b8620e66274) }

var fileDescriptor_f8be1b8620e66274 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x8a, 0xdb, 0x30,
	0x14, 0x85, 0x71, 0x7e, 0xed, 0x9b, 0x7f, 0x0d, 0xb4, 0xea, 0x94, 0x42, 0x48, 0x4b, 0xc9, 0x2c,
	0xea, 0x81, 0xce, 0xb2, 0xab, 0x64, 0xba, 0x19, 0xca, 0x94, 0x92, 0x69, 0x37, 0xdd, 0x08, 0xdb,
	0x12, 0x1d, 0x51, 0xc7, 0x32, 0x96, 0x92, 0xe0, 0xa7, 0xe8, 0x23, 0xf4, 0x55, 0x8b, 0xae, 0xe4,
	0x34, 0x64, 0x60, 0x76, 0xd6, 0x77, 0x8e, 0xc8, 0x3d, 0xba, 0x27, 0xf0, 0xa2, 0x4c, 0xaf, 0x33,
	0x55, 0x18, 0x51, 0x98, 0x6b, 0xa3, 0x4a, 0x99, 0xc5, 0x65, 0xa5, 0x8c, 0x22, 0x50, 0xa6, 0xb1,
	0xe7, 0x8b, 0x3f, 0x5d, 0xe8, 0x7e, 0xb7, 0x1a, 0x19, 0x43, 0x4b, 0x72, 0x1a, 0xcc, 0x83, 0x65,
	0x7b, 0xd3, 0x92, 0x9c, 0x10, 0xe8, 0x14, 0xc9, 0x56, 0xd0, 0xd6, 0x3c, 0x58, 0x46, 0x1b, 0xfc,
	0xb6, 0x4c, 0xe7, 0xbb, 0x5f, 0xb4, 0xed, 0x98, 0xfd, 0x26, 0x73, 0x18, 0x70, 0xa1, 0xb3, 0x4a,
	0x96, 0x46, 0xaa, 0x82, 0x76, 0x50, 0x3a, 0x45, 0xe4, 0x35, 0x44, 0x52, 0xb3, 0x24, 0x33, 0x72,
	0x2f, 0x68, 0x77, 0x1e, 0x2c, 0xc3, 0x4d, 0x28, 0xf5, 0x0a, 0xcf, 0xe4, 0x0d, 0x80, 0xd4, 0xac,
	0xac, 0xe4, 0x3e, 0x31, 0x82, 0xf6, 0x50, 0x8d, 0xa4, 0xfe, 0xe6, 0x80, 0x97, 0x75, 0x29, 0x32,
	0x99, 0xe4, 0xb4, 0xdf, 0xc8, 0x0f, 0x0e, 0x90, 0x0f, 0x70, 0x61, 0xe5, 0x47, 0x75, 0x60, 0x98,
	0x90, 0x65, 0x6a, 0x2f, 0x2a, 0x1a, 0xa2, 0x6f, 0x2a, 0xf5, 0xc3, 0xa3, 0x3a, 0x60, 0xbc, 0x5b,
	0xcb, 0xc9, 0x3b, 0x18, 0xa3, 0x81, 0x6d, 0x05, 0x97, 0x09, 0x93, 0x9c, 0x46, 0x98, 0x77, 0x88,
	0xf4, 0xde, 0xc2, 0x3b, 0x6e, 0x7f, 0x33, 0xab, 0x44, 0x62, 0x04, 0x67, 0x89, 0xa1, 0x80, 0x81,
	0x22, 0x4f, 0x56, 0xc6, 0xca, 0xbb, 0x92, 0x37, 0xf2, 0xc0, 0xc9, 0x9e, 0x38, 0x99, 0x8b, 0x5c,
	0x78, 0x79, 0xe8, 0x64, 0x4f, 0x56, 0x86, 0x7c, 0x82, 0xcb, 0xe3, 0x63, 0xb0, 0x4c, 0xe5, 0xb9,
	0xc8, 0xec, 0x23, 0xb9, 0xf1, 0xe9, 0x08, 0x07, 0x7f, 0xd9, 0xbc, 0xce, 0xed, 0x51, 0x77, 0x3b,
	0x8a, 0x31, 0xee, 0x93, 0x5b, 0x63, 0xbc, 0x35, 0x93, 0xfa, 0xdc, 0x7f, 0x92, 0x24, 0xad, 0xe9,
	0x04, 0xb3, 0x36, 0x49, 0xd6, 0x35, 0x79, 0x0f, 0x93, 0x3c, 0xd1, 0x86, 0x35, 0x71, 0xd2, 0x9a,
	0x4e, 0xd1, 0x33, 0xb2, 0xf8, 0x87, 0xa3, 0xeb, 0xda, 0x2e, 0x70, 0x2b, 0x4c, 0xc2, 0xb0, 0x0f,
	0x33, 0x4c, 0x14, 0x5a, 0xf0, 0xd5, 0x76, 0xe2, 0x0a, 0xa6, 0x28, 0x9e, 0x96, 0x80, 0xa0, 0x67,
	0x62, 0xf9, 0xe7, 0x93, 0x22, 0xbc, 0x85, 0x11, 0x5a, 0x7f, 0x8b, 0xfa, 0xa0, 0x2a, 0xae, 0xe9,
	0x05, 0xfa, 0x86, 0x16, 0x7e, 0xf1, 0x6c, 0x71, 0x03, 0x3d, 0x1c, 0x5e, 0x93, 0x2b, 0xe8, 0x61,
	0x3e, 0x4d, 0x83, 0x79, 0x7b, 0x39, 0xf8, 0x38, 0x8b, 0xff, 0x17, 0x37, 0x46, 0xcf, 0xc6, 0x1b,
	0x16, 0x7f, 0x03, 0x88, 0x90, 0xdc, 0x8b, 0x62, 0x47, 0x5e, 0x41, 0xe8, 0xda, 0x70, 0x2c, 0x74,
	0x1f, 0xcf, 0x77, 0x9c, 0x5c, 0x42, 0x58, 0x2a, 0x2d, 0x71, 0xca, 0x16, 0x4a, 0xc7, 0xf3, 0xd9,
	0xde, 0xdb, 0xcf, 0xef, 0xbd, 0xf3, 0xfc, 0xde, 0xbb, 0x67, 0x7b, 0x5f, 0x47, 0x3f, 0xfb, 0x7e,
	0xf4, 0xb4, 0x87, 0x7f, 0xc3, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x03, 0xe7, 0x52, 0x49,
	0xa0, 0x03, 0x00, 0x00,
}
